"""Role Project favorite table added

Revision ID: 1b86fe4e47d7
Revises: e00be8758dad
Create Date: 2025-08-05 11:16:58.252027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b86fe4e47d7'
down_revision: Union[str, None] = 'e00be8758dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favoritable_type', sa.String(length=50), nullable=False),
    sa.Column('favoritable_id', sa.Integer(), nullable=False),
    sa.Column('favorited_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'favoritable_type', 'favoritable_id', name='unique_user_favorite')
    )
    op.create_index(op.f('ix_project_favorites_id'), 'project_favorites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_favorites_id'), table_name='project_favorites')
    op.drop_table('project_favorites')
    # ### end Alembic commands ###
